version: "3.8"
services:
  user-svc:
    image: user-svc/user-svc:latest
    command: ["./user-svc", "--hmac-secret", "hmac-secret", "--salt", "salt", "--addr", "0.0.0.0:80", "--db-connection", "host=db port=5432 user=user password=password dbname=user-svc sslmode=disable"]
  source:
    image: user-svc/source:latest
    command: ["go", "test", "-v", "pkg/test/integration_test.go", "--user-svc-addr", "user-svc:80", "--db-connection", "host=db port=5432 user=user password=password dbname=user-svc sslmode=disable"]
  db:
    image: postgres
    environment:
      POSTGRES_DB: user-svc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password